ARG FROM_IMAGE=osrf/ros:foxy-desktop
FROM $FROM_IMAGE
USER root

RUN apt upgrade -y

RUN apt-get update -qq && apt-get install -y \
    python3-pip \
    curl \
    git \
    wget \
    git \
    cmake \
    ninja-build \
    udev \
    gperf

WORKDIR /home
RUN mkdir setup
WORKDIR /home/setup

# Update cmake for zephyr
COPY install_scripts/cmake_update.sh .
RUN chmod +x cmake_update.sh
# RUN ./cmake_update.sh

# Install zephyr
COPY install_scripts/zephyr_install.sh .
RUN chmod +x zephyr_install.sh
RUN ./zephyr_install.sh

COPY install_scripts/zephyr_install2.sh .
RUN chmod +x zephyr_install2.sh
# RUN ./zephyr_install2.sh

COPY install_scripts/zephyr_install_b.sh .
RUN chmod +x zephyr_install_b.sh
# RUN ./zephyr_install_b.sh

# Install microros
# COPY install_scripts/microros_install.sh .
# RUN chmod +x microros_install.sh
# RUN ./microros_install.sh

